attention_resolutions: 32,16,8
class_cond: true
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_heads: 4
num_res_blocks: 2
resblock_updown: true
use_fp16: true
use_scale_shift_norm: true
timestep_respacing: '250'
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
max_step: 200000
use_checkpoint: false
use_new_attention_order: false
image_size: 256
clip_denoised: True
num_samples: 10
batch_size: 4
use_ddim: False
model_path: ./logs/model040000.pt
