name: taming
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=20.3
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-lightning=1.9.4
  - numpy=1.24.3
  - pip:
    - wandb==0.15.2
    - albumentations==1.3.0
    - opencv-python==4.7.0.72 # ==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.0.6
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - more-itertools>=8.0.0
    - transformers==4.3.1
    - packaging==21.3 # packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'
    - -e .
