model:
  base_learning_rate: 4.5e-6
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    first_stage_key: image
    cond_stage_key: class_label
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 16384
        block_size: 254
        n_layer: 48
        n_head: 24
        n_embd: 1536
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        embed_dim: 256
        n_embed: 16384
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.DummyLoss
    cond_stage_config:
      target: taming.modules.util.Labelator
      params:
        n_classes: 30

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    wrap: false
    train:
      target: taming.data.custom_cond_cls.CustomTrain
      params:
        # training_images_list_file: /root/autodl-tmp/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/train.flist
        training_images_list_file: /data/cyc/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/train.flist
        size: 64 # 256
    validation:
      target: taming.data.custom_cond_cls.CustomTest
      params:
        # test_images_list_file: /root/autodl-tmp/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/test.flist
        test_images_list_file: /data/cyc/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/test.flist
        size: 64 # 256

lightning:
    trainer: 
      accumulate_grad_batches: 8
      precision: 16
      accelerator: 'gpu'
      devices: [0, 1]
      max_epochs: 60