model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    ckpt_path: ./logs/vqgan_imagenet_f16_16384.ckpt
    embed_dim: 256
    n_embed: 16384
    monitor: val/rec_loss
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4] # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        disc_num_layers: 2
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 6
    train:
      target: taming.data.custom_cond_cls.CustomTrain
      params:
        training_images_list_file: /root/autodl-tmp/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/train.flist
        # training_images_list_file: /data/cyc/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/train.flist
        size: 256
    validation:
      target: taming.data.custom_cond_cls.CustomTest
      params:
        test_images_list_file: /root/autodl-tmp/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/test.flist
        # test_images_list_file: /data/cyc/2023-generative-remote-sensing/datasets/data/cls/AID_test0.2/test.flist
        size: 256

lightning:
  trainer:
    accumulate_grad_batches: 4
    # precision: 16 # may lead to NaN
    accelerator: gpu
    devices: [0, 1, 2]
    max_epochs: 150
    log_every_n_steps: 20
    # deterministic: True # may slow your machine
